name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
           node-version: [16.x,18.x]
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Use Nodejs ${{matrix.node-version}}
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-version}}
            cache: 'npm'
        - name: Install dependencies
          run: npm ci
        - name: Run Linter
          run: npm run lint
        - name: Run Tests
          run: npm test
  
  deploy: 
      needs:  build-and-test
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Deploy to server ( example using SSH)
          uses: appleboy/ssh-action@v1.0.0
          with: 
            host: 'localhost'
            username: 'awaisniaz@1234'
            key: 'Awaisnisz@'
            script: |
               cd /var/www/myapp
               git pull origin master
               npm install
               pm2 restart myapp



    